### ISSUE TITLE
Undefined method 'map'

### ISSUE THREAD

**Issue by dawidd6** [gelraen/homebrew-autoremove#1]
Thanks for this external command, would love to use it, but I get this error while executing it:

```sh
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/gelraen/homebrew-autoremove/cmd/brew-autoremove:44:in `block (2 levels) in <main>': undefined method `map' for nil:NilClass (NoMethodError)
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/gelraen/homebrew-autoremove/cmd/brew-autoremove:44:in `map'
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/gelraen/homebrew-autoremove/cmd/brew-autoremove:44:in `block in <main>'
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/gelraen/homebrew-autoremove/cmd/brew-autoremove:43:in `each'
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/gelraen/homebrew-autoremove/cmd/brew-autoremove:43:in `<main>'
```

**Comment by dawidd6** [comment]
It seems like `runtime_dependencies` json field is not present in every formulae object.

**Comment by mfleucha** [comment]
@dawidd6 how did you fix the problem in the end? It would be very helpful if there was a fix - it does not really seem that the error has to do with the runtime_dependencies - it blocks the complete action of the script unfortunately...

**Comment by dawidd6** [comment]
@mfleucha I made my own script: https://github.com/dawidd6/homebrew-autoremove
